# Generated by Django 4.1.3 on 2022-12-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deparment_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
