# Generated by Django 4.1.3 on 2022-12-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
